sudo: required
services:
- docker
language: go
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: XSUnYpZ1aKQgceYw65WVFr3J7eeKIOygNJzlLaYfEELM5ouLdjS2KRjadCCfx9Sk8s9uQxwlPExabQXaWiVwNekG9jlS1wYrnr9dsNcoFd+zImyaz8vYM0wx98gboYl8ehaQv2086+DD9YAQDs7sF2z3q+ECXrkyGlYOIUzowenvvkP1S29O481iIwJTyxds8t73tThLQCOn2KwmmWsA59Gnz71IlnMJ76R8ibCDBcFsIgQVWJ8xXKIDARr97LrGo/Aau2HXJW/f598SYwyvBapRS//IwTQwANSc9zFcjVP+DuUSLUwKkTJCrHdgmXHPknmYvOD4jt3rw4BABDwZfmozKDFeoinDoSm1YJ3/oKcSEPO+8D4LnXFBdkLbH9XcKe7Ncofm+En+FrGbGUuqOW/OuV6xYHbvNmd62IR54T4WdmjC+PJbDrZtBYXRPbu24CieatBwndJGwkOl8a9uzqUf4y4b0ON370XtV0Ca6r+2Ow78HTWCbbUZiHx5FURL3HPDnUNL9Fz2nUe5RHjxfOURx6978oPYE4K3TEJWeDvqJlo8ygYx48bfbU1JeCEFgNCSW5hqtfw5HFZ3ZHz2a8UzREYUY/GJSmRdRrc0dhnEUHr2kip9FzJAVmtptg2MfbTd8WqKz/jmnQxV30SVi1sq7asUcUD1OxUQVJSmZk8=
  - secure: GMlDqZE+OK1V8TJ+LgnXeeu6YB1sgcvVADzJiePUCxxZGTpNLLD3NMBBWD4rJApD8JquiemSudfqk9Fz9DALR0WhfUzEeYv9kzWpyj9loMmx7InFt+q+VwPyU/R0+S/uEKuN0eSoeFrwT4KdbG+zlaJO9HYk2XgsRpBKiVJZoVNZ+udGu4sAE84kkBTJFZd55mMiYMX9D6k14vJ5MCYCOiwaon7Uyg2GX4pS46iyEeEidK6DLiNO0kgPQJ+9wXEdnIOLX5FIGTdQXbfhX6iPlk7OhKgZiQkzpfx1Y0wS6k0nVdqnSsKyLZxqUUx5UpciYp34MUkyDgC9mKO1m+sI3/NvpOSmPN3iFH3hHNC39Raft2FOWns5EZHLo9y/e8czD7g/LnggYQlw4gWwyfX6/BQQk7KJKVx8xlkBR4k2oDw5gMZAbcZ1GvNmucshJBOZItpimK/Jag2u8rqd1GLXQhEiB/Ey74S1Acb6WFYQdVGaCenkWP6gyqkuxdNnyA6WjrbylDayiBe+pGNa5QfWjxuD0x7RQ1AaN/V+HH63w9Wbwj8ulhgy/eeKhTrgd2FEqG9bHbNupNM6Plp30v3CU5TdTwneP9wls0sYbMxZwIoRqyYx0RGmClT0Pp5XW3q8UaCtgXbtkq09nb9Xspm8LW8py9oAXjqLmVC6GRVEWhs=
  - secure: dtA08LLdNbuUz4bgGoAsxXyVDEUmL7it5IS5N/YhYg96lu2PtHaLPs7p14gQIdPj6LrFv2o5I2aLiczs14adGaBBhpIsG6M3V3ZcwWnROe3VXFypa9VNOPueP5ApHa168VFMznYCbZh3hAu2jiCBr90J6pf7WECdKaLOACARyp1in0LAx9VyNlge3d4iNKli0SwLuCjaxS2VxL2M1Je9T+wlyLPNP8eXdrC0t0dEvr4edxHM5CAvVflBt8ULV2R3ESvjKjUNski/ZYPeOCVZezhEHfQ1RH0l0nH/UiFlXh5/d9hKUId6vATGIu4bUUGtWWrv0zkkw/beC3DJ9gA6UTs6FbDMHkpUUDvgPKqpDtufIPCDus4WPTaBAngqNPxc2rHS0J8WYRZ45fvSMUin8tokx2VwUiOcaK9CIpn/fsWCwfg3jWuCFmGdKcUeJ002pqJJ1IODU4noTWghkigaRD7GncgPnbaNJZfVcnu6hPmASztCyV57M7q9gndW8Go0srKYfrFO6zf9TzvSkFEu5UlbLP8VpYfyH6OjdjK8fNz3Ul608856eTmcTs0eTgIpCYfkENE9pr+JIlnDzwdP9yOAV+MdATNo6BJtDotES7qXV9e9YQV5W2hqXxMnDi/SwwpdnzeXBmxIGPHfY2wbZsZG2VpgnyRLjnwQyWn4yv4=
go:
- 1.6
install:
- go get -t -v ./...
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- "$HOME/gopath/bin/goveralls -service=travis-ci"
- go test -v ./...
- CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -o ./deploy-mongodb

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=supergiant/deploy-mongodb
  - export TAG=`if [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; elif [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then echo "unstable-${TRAVIS_BRANCH}"; else echo $TRAVIS_TAG ; fi`
  - docker build -t $REPO:$TAG .
  - docker push $REPO

notifications:
  slack:
    secure: lz2sOKGL9r7ZOM8tXY66QdP+QDiNZJ7ewpc9HPJmnDvPd1P2hj6BGAeeMNKBXHVmK69BD7DNeqvpd9vdgSXcCBLEga6o8xi1UrzxoU4fSa4MQs3pwNGot9PH3fY8yYPOJb2WU5TEKz68KniXL03n3Cr/4lqSE5GpaenhJLC2wrQCLTHthh/iOYgEe5j4MEPZMVPC9GHYS8cUBdTEu+ZiTkYSQGpccSB6z4F44UNlTT9z86fcajTF3Kxza/Gw2VDwzTwy0oYcGzBUF53Y38cpwCqhJ9Q/1q/mawUPOinCtQHOUYRYseW6QC5pO9UtijEgr3ROkavA7YloqbF0ol1SsRG0cAD0Fqi1CrcJ8TtEaeG/hlB2S73MzHw4bzYCdbxbLeRtsQCMxdHsGS2oFJXPRpB5VNOKH3BSDrY7b5jkhehH8AsADuCv7JaXtN39cOmtMzc/BM/QKkpsf93hlqiOUsA1lzRlSRVGoQDgY+PX2YrXsVliCF0mTSnGC7VxQPhwsbsFmz8CkxdTzvI4Yj2lc3YrTVi8h0jm3aWlln5KgG0wR6b8FJ6qetoEQL0kFi569LrT94YAGzjtTXbhGZcl2IL5dh5FETEFlAplQwvvsrk8xAD7fNoyogXC/O4s01/o21GAhF8T8JLJpkekIXA2SjOAGiUJZXmiL/GplPCC9p4=
